name: Deploy to Main GitHub Pages Site

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-main-site:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout AWS Field Guide
      uses: actions/checkout@v4
      with:
        path: aws-field-guide
        
    - name: Checkout Main Site
      uses: actions/checkout@v4
      with:
        repository: cncoder/cncoder.github.io
        token: ${{ secrets.GITHUB_TOKEN }}
        path: main-site
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install HonKit
      run: npm install -g honkit
      
    - name: Build GitBook
      run: |
        cd aws-field-guide
        honkit install
        honkit build . _book
        
    - name: Deploy to main site
      run: |
        # Create aws-field-guide directory in main site
        mkdir -p main-site/aws-field-guide
        
        # Copy built files
        cp -r aws-field-guide/_book/* main-site/aws-field-guide/
        
        # Update main site index if needed
        cd main-site
        
        # Add AWS Field Guide link to main page (if index.html exists)
        if [ -f index.html ]; then
          # Add link to AWS Field Guide (you can customize this)
          echo "<!-- AWS Field Guide Book available at /aws-field-guide/ -->" >> index.html
        fi
        
        # Commit and push changes
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update AWS Field Guide Book" || exit 0
        git push
